#! /bin/sh
# Distributed under the terms of the GNU General Public License, v2 or later
# Copyright (C) 2010 Jarek Bojko
# Contact: vazir.pl@gmail.com      

case "$1" in
  start)
    echo "Starting Wiimotedev-daemon "
    start-stop-daemon --start -q --exec /usr/sbin/wiimotedev-daemon
    ;;
  stop)
    echo "Stopping Wiimotedev-daemon"
    start-stop-daemon --stop -q --pidfile /var/run/wiimotedev-daemon.pid
    ;;
esac

exit 0