#! /bin/sh
# Distributed under the terms of the GNU Lesser General Public License, v2.1 or later
# Copyright (C) 2010 Jarek Bojko
# Contact: vazir.pl@gmail.com

### BEGIN INIT INFO
# Provides:          wiimotedev-uinput
# Required-Start:    bluetooth
# Required-Stop:     bluetooth
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: wiimotedev uinput
### END INIT INFO

PIDFILE=/var/run/wiimotedev-uinput.pid
SERVICE=/usr/sbin/wiimotedev-uinput
GROUP=uinput
CONFIG=/etc/wiimotedev/uinput.conf

start() {

  if [ -z $(cat /etc/group | grep $GROUP) ]; then
    groupadd $GROUP &> /dev/null

    if [ ! -n $(cat /etc/group | grep $GROUP) ]; then
      echo "Cannot add new group $GROUP"
      exit 1
    fi

  fi

  if [ -f "$PIDFILE" ]; then
    echo "Already running. Please remove $PIDFILE to force start."
    exit 1
  fi

  if [ -x "$SERVICE" ]; then
    start-stop-daemon --start -q -x "$SERVICE" --group "$GROUP"
  fi

}

stop() {

  if [ -f "$PIDFILE" ]; then
    start-stop-daemon --stop -q -p "$PIDFILE" --group "$GROUP"
    rm -f $PIDFILE &> /dev/null
  else
    echo "Please start service first."
    exit 1
  fi

}

case "$1" in
  start)
    echo "Starting Wiimotedev-uinput"
    start
    ;;
  stop)
    echo "Stopping Wiimotedev-uinput"
    stop
    ;;
  restart)
    echo "Stopping Wiimotedev-uinput"
    stop
    sleep 1
    echo "Starting Wiimotedev-uinput"
    start
    ;;
  *)
    echo $"Usage: $0 {start | stop | restart }"
    ;;
esac

exit 0
