#!/bin/sh
# Distributed under the terms of the GNU Lesser General Public License, v2.1 or later
# Copyright (C) 2010 Korneliusz Jarzębski
# Contact: public@santyago.pl

PIDFILE=/var/run/wiimotedev-daemon.pid
SERVICE=/usr/sbin/wiimotedev-daemon
GROUP=wiimotedev
CONFIG=/etc/wiimotedev/wiimotedev.conf

wiimotedev_start() {
  if [ -x /usr/sbin/wiimotedev-daemon ]; then
    /usr/sbin/wiimotedev-daemon
  fi
}

wiimotedev_stop() {
  if [ -e "$PIDFILE" ]; then
    kill $(cat $PIDFILE)
    rm -f $PIDFILE
  fi
  killall wiimotedev-daemon 1> /dev/null 2> /dev/null
}

wiimotedev_reload() {
  if [ ! -f "$PIDFILE" ]; then
    echo " -- \"${PIDFILE}\" file does not exist"
    return 1
  fi

  if [ ! -f "$CONFIG" ]; then
    echo " -- \"${CONFIG}\" configuration does not exist"
    return 1
  fi


  if [ $(cat /proc/$(cat /var/run/wiimotedev-daemon.pid)/cmdline) != $SERVICE ]; then
    echo " -- Unable to find service"
    return 1
  fi

  S1=$(dbus-send \
            --system \
            --dest=org.wiimotedev.daemon \
	    --type=method_call \
	    --print-reply \
	    --reply-timeout=3000 \
	    /service \
	    org.wiimotedev.service.dbusReloadSequenceList)

  if [ -n "$(echo ${S1} | grep "boolean true")" ]; then
    echo " -- Configuration reloaded successful"
  else
    echo " -- Cannot reload configuration, dbus fail?"
    return 1
  fi
  
}

case "$1" in
    start)
	echo "Starting Wiimotedev-daemon"
        wiimotedev_start
        ;;
    stop)
	echo "Stopping Wiimotedev-daemon"
        wiimotedev_stop
        ;;
    restart)
	echo "Restarting Wiimotedev-daemon"
        wiimotedev_stop
        sleep 1
        wiimotedev_start
        ;;
    reload)
	echo "Reloading Wiimotedev-daemon"
	wiimotedev_reload
        ;;
    *)
        echo $"Usage: $0 {start | stop | reload | restart }"
        ;;
esac