#!/bin/sh
# Distributed under the terms of the GNU Lesser General Public License, v2.1 or later
# Copyright (C) 2010 Korneliusz Jarzębski
# Contact: public@santyago.pl

PIDFILE=/var/run/wiimotedev-uinput.pid
SERVICE=/usr/sbin/wiimotedev-uinput
GROUP=uinput
CONFIG=/etc/wiimotedev/uinput.conf

start() {

  if [ -z $(cat /etc/group | grep $GROUP) ]; then
    groupadd $GROUP &> /dev/null

    if [ ! -n $(cat /etc/group | grep $GROUP) ]; then
      echo "Cannot add new group $GROUP"
      exit 1
    fi

  fi

  if [ -f "$PIDFILE" ]; then
    echo "Already running. Please remove $PIDFILE to force start."
    exit 1
  fi

  if [ -x "$SERVICE" ]; then
    ($SERVICE)
  fi

}

stop() {

  if [ -f "$PIDFILE" ]; then
    kill -s 3 $(cat $PIDFILE) &> /dev/null
    rm -f $PIDFILE &> /dev/null
  else
    echo "Please start service first."
    exit 1
  fi

}

case "$1" in
  start)
    echo "Starting Wiimotedev-uinput"
    start
    ;;
  stop)
    echo "Stopping Wiimotedev-uinput"
    stop
    ;;
  restart)
    echo "Stopping Wiimotedev-uinput"
    stop
    sleep 1
    echo "Starting Wiimotedev-uinput"
    start
    ;;
  *)
    echo $"Usage: $0 {start | stop | restart }"
    ;;
esac
