#!/bin/sh
# Distributed under the terms of the GNU Lesser General Public License, v2.1 or later
# Copyright (C) 2010 Korneliusz Jarzębski
# Contact: public@santyago.pl

PIDFILE=/var/run/wiimotedev-io.pid
SERVICE=/usr/sbin/wiimotedev-io
GROUP=io
CONFIG=/etc/wiimotedev/io.conf

start() {

  if [ -z $(grep ^$GROUP: /etc/group) ]; then
    groupadd $GROUP &> /dev/null

    if [ ! -n $(grep ^$GROUP: /etc/group) ]; then
      echo "Cannot add new group $GROUP"
      exit 1
    fi

  fi

  if [ -f "$PIDFILE" ]; then
    echo "Already running. Please remove $PIDFILE to force start."
    exit 1
  fi

  if [ -x "$SERVICE" ]; then
    ($SERVICE)
  fi

}

stop() {

  if [ -f "$PIDFILE" ]; then
    kill -s 3 $(cat $PIDFILE) &> /dev/null
    rm -f $PIDFILE &> /dev/null
  else
    echo "Please start service first."
    exit 1
  fi

}

case "$1" in
  start)
    echo "Starting Wiimotedev-io"
    start
    ;;
  stop)
    echo "Stopping Wiimotedev-io"
    stop
    ;;
  restart)
    echo "Stopping Wiimotedev-io"
    stop
    sleep 1
    echo "Starting Wiimotedev-io"
    start
    ;;
  *)
    echo $"Usage: $0 {start | stop | restart }"
    ;;
esac
