#!/bin/sh
# Distributed under the terms of the GNU Lesser General Public License, v2.1 or later
# Copyright (C) 2010 Bartlomiej Burdukiewicz
# Contact: bartlomiej.burdukiewicz@gmail.com

PIDFILE=/var/run/wiimotedev-io.pid
SERVICE=/usr/sbin/wiimotedev-io
GROUP=io
CONFIG=/etc/wiimotedev/io.conf

. /etc/rc.conf
. /etc/rc.d/functions

start() {

  if [ -z $(cat /etc/group | grep $GROUP) ]; then
    groupadd $GROUP &> /dev/null

    if [ ! -n $(cat /etc/group | grep $GROUP) ]; then
      stat_fail
      echo "Cannot add new group $GROUP"
      exit 1
    fi

  fi

  if [ -f "$PIDFILE" ]; then
    stat_fail
    echo "Already running. Please remove $PIDFILE to force start."
    exit 1
  fi

  if [ -x "$SERVICE" ]; then
    ($SERVICE)
    stat_done
  else
    stat_fail
  fi

}

stop() {

  if [ -f "$PIDFILE" ]; then
    kill -s 3 $(cat $PIDFILE) &> /dev/null
    rm -f $PIDFILE &> /dev/null
    stat_done
  else
    stat_fail
    echo "Please start service first."
    exit 1
  fi

}

case "$1" in
  start)
    stat_busy "Starting Wiimotedev-io"
    start
    ;;
  stop)
    stat_busy "Stopping Wiimotedev-io"
    stop
    ;;
  restart)
    stat_busy "Stopping Wiimotedev-io"
    stop
    sleep 1
    stat_busy "Starting Wiimotedev-io"
    start
    ;;
  *)
    echo $"Usage: $0 {start | stop | restart }"
    ;;
esac
