#!/bin/sh
# Distributed under the terms of the GNU Lesser General Public License, v2.1 or later
# Copyright (C) 2010 Bartlomiej Burdukiewicz
# Contact: dev.strikeu@gmail.com

PIDFILE=/var/run/wiimotedev-daemon.pid
SERVICE=/usr/sbin/wiimotedev-daemon
GROUP=wiimotedev
CONFIG=/etc/wiimotedev/wiimotedev.conf

. /etc/rc.conf
. /etc/rc.d/functions

start() {

  if [ -z $(cat /etc/group | grep $GROUP) ]; then
    groupadd $GROUP &> /dev/null

    if [ ! -n $(cat /etc/group | grep $GROUP) ]; then
      stat_fail
      echo "Cannot add new group $GROUP"
      exit 1
    fi

  fi

  if [ -f "$PIDFILE" ]; then
    stat_fail
    echo "Already running. Please remove $PIDFILE to force start."
    exit 1
  fi

  if [ -x "$SERVICE" ]; then
    ($SERVICE)
    stat_done
  else
    stat_fail
  fi

}

stop() {

  if [ -f "$PIDFILE" ]; then
    kill -s 3 $(cat $PIDFILE) &> /dev/null
    rm -f $PIDFILE &> /dev/null
    stat_done
  else
    stat_fail
    echo "Please start service first."
    exit 1
  fi

}

reload() {

  if [ ! -f "$PIDFILE" ]; then
    stat_fail
    echo "Please run service first."
    exit 1
  fi

  S1=$(dbus-send --system --dest=org.wiimotedev.daemon \
       --type=method_call --print-reply --reply-timeout=3000 \
       /service org.wiimotedev.service.dbusReloadSequenceList)

  if [ -n "$(echo ${S1} | grep "boolean true")" ]; then
    stat_done
  else
    stat_fail
    exit 1
  fi

}

case "$1" in
  start)
    stat_busy "Starting Wiimotedev-daemon"
    start
    ;;
  stop)
    stat_busy "Stopping Wiimotedev-daemon"
    stop
    ;;
  restart)
    stat_busy "Stopping Wiimotedev-daemon"
    stop
    sleep 1
    stat_busy "Starting Wiimotedev-daemon"
    start
    ;;
  reload)
    stat_busy "Reloading Wiimotedev-daemon"
    reload
    ;;
  *)
    echo $"Usage: $0 {start | stop | reload | restart }"
    ;;
esac
